CXX := g++

CXXFLAGS := -std=c++11

OBJS = CPUTest.o Memory.o Cart.o MockCart.o

all: cputest

CPU.cpp: generate_ops.py CPU.pre.cpp
	./generate_ops.py

CPU.o: CPU.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $^

cputest: $(OBJS) CPU.o
	$(CXX) -o $@ $^

clean:
	rm -f *.o cputest CPU.cpp
