CXX := g++

CXXFLAGS := -std=c++11

OBJS = Cart.o Input.o LCD.o Memory.o Emulator.o

all: emulator

CPU.cpp: generate_ops.py CPU.pre.cpp
	./generate_ops.py

CPU.o: CPU.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $^

emulator: $(OBJS) CPU.o
	$(CXX) -o $@ $^

clean:
	rm -f *.o emulator CPU.cpp
