CXX := g++

CXXFLAGS := -std=c++11 `sdl2-config --cflags`

OBJS = Cart.o SDL_Input.o SDL_LCD.o Memory.o Emulator.o

all: emulator

CPU.cpp: generate_ops.py CPU.pre.cpp
	./generate_ops.py

CPU.o: CPU.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $^

emulator: $(OBJS) CPU.o
	$(CXX) `sdl2-config --libs` -o $@ $^

clean:
	rm -f *.o emulator CPU.cpp
